### ISSUE TITLE
Many .gitignore files

### ISSUE THREAD

**Issue by cchoirat** [EricaMoreira/SemSeg#4]
You could have one (see, e.g., https://git-scm.com/docs/gitignore)

**Comment by EricaMoreira** [comment]
Thank you for the suggestion. The purpose of the gitignore files is so that we can include empty directories in the repo (in which users will put the images they are analyzing after they have cloned the repo locally). This is just to make things simpler and easier for the user. We will test whether this would be possible with a single gitignore, and we will update if we feel this would be a better solution.
